### ISSUE TITLE
irrc fails only when run inside a Minitest test

### ISSUE THREAD

**Issue by yjukaku** [codeout/irrc#3]
Hey, thanks for your work on this gem.

I realize this isn't exactly an issue with irrc, but I can't figure out any way around it. I was hoping you could help debug this.

### Test
Run with `ruby -Ilib:test test/thread_test.rb`
```ruby
require 'minitest/autorun'
require 'irrc'

class ThreadTest < Minitest::Test

  def test_irrc
    client = Irrc::Client.new
    client.query :radb, 'something'
    results = client.perform
  end

end
```

### Output
```
ThreadTest#test_irrc:
fatal: No live threads left. Deadlock?
4 threads, 4 sleeps current:0x00007fb85440d710 main thread:0x00007fb852703f40
* #<Thread:0x00007fb85307ef00 sleep_forever>
   rb_thread_t:0x00007fb852703f40 native:0x00007fffb871c380 int:0
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:64:in `join'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:64:in `block in run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:64:in `each'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:64:in `run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:86:in `perform'
   test/thread_test.rb:9:in `test_irrc'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/test.rb:195:in `capture_exceptions'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:265:in `time_it'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/test.rb:94:in `block in run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/test.rb:211:in `with_info_handler'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/test.rb:93:in `run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:960:in `run_one_method'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:334:in `run_one_method'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:321:in `block (2 levels) in run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `each'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `block in run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:319:in `run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `map'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `__run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:136:in `run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
* #<Thread:0x00007fb852913298@/Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/parallel.rb:28 sleep_forever>
   rb_thread_t:0x00007fb85450c200 native:0x000070000fc5d000 int:0
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/parallel.rb:30:in `pop'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/parallel.rb:30:in `block (2 levels) in start'
* #<Thread:0x00007fb852913158@/Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/parallel.rb:28 sleep_forever>
   rb_thread_t:0x00007fb854536f00 native:0x000070000fd60000 int:0
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/parallel.rb:30:in `pop'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.3/lib/minitest/parallel.rb:30:in `block (2 levels) in start'
* #<Thread:0x00007fb852910c78@/Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:59 sleep_forever>
   rb_thread_t:0x00007fb85440d710 native:0x000070000fe63000 int:0
    depended by: tb_thread_id:0x00007fb852703f40
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/runner.rb:15:in `pop'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/runner.rb:15:in `block in run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/runner.rb:6:in `loop'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/runner.rb:6:in `run'
   /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:61:in `block (3 levels) in run'

    /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:64:in `join'
    /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:64:in `block in run'
    /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:64:in `each'
    /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:64:in `run'
    /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/irrc-0.2.0/lib/irrc/client.rb:86:in `perform'
    test/thread_test.rb:9:in `test_irrc'
```

Any ideas?

**Comment by codeout** [comment]
Hi yjukaku,

Thanks for your report, it looks like a bug.
Could you try the latest code? I've just pushed a fix.

**Comment by yjukaku** [comment]
Hey @codeout , yep, looks like it fixed the bug 👏 . Thanks for your quick work! Any chance of a gem release?

**Comment by codeout** [comment]
0.2.1 has been published 🚀
